In [1]:
import cv2
import os
import numpy as np

In [2]:
img = cv2.imread(r"C:\Users\20191039\Desktop\OF\new_deep\deeplearning-notebooks\dataset\000144_10.png")

In [11]:
cv2.imshow("Image", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
def load_flow_from_png(png_path):
    # The -1 is here to specify not to change the image depth (16bit), and is compatible
    # with both OpenCV2 and OpenCV3
    flo_file = cv2.imread(png_path, -1)
    flo_img = flo_file[:,:,2:0:-1].astype(np.float32)
    invalid = (flo_file[:,:,0] == 0)
    flo_img = flo_img - 32768
    flo_img = flo_img / 64
    flo_img[np.abs(flo_img) < 1e-10] = 1e-10
    flo_img[invalid, :] = 0
    return(flo_img)

In [111]:
def inverse_load_flow_from_png(flo_img, img):
    flo_img = flo_img * 64
    flo_img = flo_img + 32768
    # flo_img = flo_img[:,:,::-1].astype(np.float32)
    zeros = np.zeros((len(img),len(img[0]),1))
    new = np.concatenate((zeros, flo_img), axis = 2)
    cv2.imwrite(r"C:\Users\20191039\Desktop\OF\new_deep\deeplearning-notebooks\output\test.png", new)
    return new

In [112]:
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder,filename))
        #img = load_flow_from_png(png_path)
        if img is not None:
            images.append(img)
    return images

In [131]:
images = load_images_from_folder(r"D:\Datasets\KITTI\training\flow_noc")

In [114]:
zeros = np.zeros((len(img),len(img[0]),1))
zeros.shape
# img.shape

(375, 1242, 1)

In [115]:
im1 = images[2]
im2 = images[3]
im1_grey = cv2.cvtColor(im1,cv2.COLOR_BGR2GRAY)
im2_grey = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
flow12 = cv2.calcOpticalFlowFarneback(im1_grey, im2_grey, None, 0.5, 3, 15, 3, 5, 1.2, 0)
final_flow = inverse_load_flow_from_png(flow12, im1)

In [129]:
np.unique(flow12[...,0])

array([-0.02201841, -0.02068975, -0.02009461, ...,  0.01640995,
        0.0165925 ,  0.01815298], dtype=float32)

In [122]:
test_flow = load_flow_from_png(r"D:\Datasets\KITTI\training\flow_noc\000000_10.png")

In [124]:
np.unique(test_flow[...,1])

array([-7.171875, -7.15625 , -7.140625, ..., 54.25    , 54.265625,
       54.28125 ], dtype=float32)

In [7]:
cv2.imshow("Image", test_flow)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(4.5.1) c:\users\appveyor\appdata\local\temp\1\pip-req-build-wvn_it83\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xeee51b91::Set<3,4,-1>,struct cv::impl::A0xeee51b91::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 2


In [132]:
import cv2 as cv
index = 144
for i in range(0, len(images), 2):
    hsv = np.zeros_like(images[i])
    hsv[...,1] = 255
    prvs = cv.cvtColor(images[i], cv.COLOR_BGR2GRAY)
    next = cv.cvtColor(images[i + 1], cv.COLOR_BGR2GRAY)
    flow = cv.calcOpticalFlowFarneback(prvs, next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    mag, ang = cv.cartToPolar(flow[...,0], flow[...,1])
    hsv[...,0] = ang*180/np.pi/2
    zeros = np.zeros((len(images[i]),len(images[i][0]),1))
    new = np.concatenate((zeros, flow), axis = 2)
    # var = np.zeros_like(images[i])
    # var = flow[only_zeros, ...]
    #hsv[...,2] = cv.normalize(mag,None,0,255,cv.NORM_MINMAX)
    #hsv[...,2] = mag
    #bgr = cv.cvtColor(hsv,cv.COLOR_HSV2BGR)
    cv2.imwrite(r"C:\Users\20191039\Desktop\OF\new_deep\deeplearning-notebooks\output\000" + str(index + i) + "_10.png", new)

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wvn_it83\opencv\modules\video\src\optflowgf.cpp:1114: error: (-215:Assertion failed) prev0.size() == next0.size() && prev0.channels() == next0.channels() && prev0.channels() == 1 && pyrScale_ < 1 in function 'cv::`anonymous-namespace'::FarnebackOpticalFlowImpl::calc'


In [18]:
flow.shape

(1, 376, 1241, 2)

In [27]:
flow.shape
check = flow.reshape(flow.shape + (1,))
check.shape

(375, 1242, 2, 1)

In [80]:
width = len(images[i][0])
height = len(images[i])
only_zeros = np.zeros((height, width))
np.shape(only_zeros)

(375, 1242)

In [42]:
np.unique(new[...,1])

array([-79.89870453, -79.87413788, -79.76878357, ...,  38.55600739,
        38.58072662,  38.58291245])

In [57]:
np.shape(img2)

(375, 1242, 3)

In [45]:
type(flow[0])

int

In [28]:
img2 = cv2.imread(r"D:\Datasets\KITTI\training\flow_noc\000156_10.png")

In [34]:
np.unique(img2[..., 2])

array([128, 129, 130], dtype=uint8)

In [30]:
img_flow = cv2.imread(r"C:\Users\20191039\Desktop\OF\new_deep\deeplearning-notebooks\output\file56.png")

In [35]:
np.unique(img_flow[..., 2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40], dtype=uint8)

In [ ]:
import numpy as np
import cv2 as cv
#cap = cv.VideoCapture(cv.samples.findFile("vtest.avi"))
#ret, frame1 = cap.read()
prvs = cv.cvtColor(frame1,cv.COLOR_BGR2GRAY)
hsv = np.zeros_like(frame1)
hsv[...,1] = 255
while(1):
    #ret, frame2 = cap.read()
    next = cv.cvtColor(frame2,cv.COLOR_BGR2GRAY)
    flow = cv.calcOpticalFlowFarneback(prvs,next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    mag, ang = cv.cartToPolar(flow[...,0], flow[...,1])
    hsv[...,0] = ang*180/np.pi/2
    hsv[...,2] = cv.normalize(mag,None,0,255,cv.NORM_MINMAX)
    bgr = cv.cvtColor(hsv,cv.COLOR_HSV2BGR)
    cv.imshow('frame2',bgr)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break
    elif k == ord('s'):
        cv.imwrite('opticalfb.png',frame2)
        cv.imwrite('opticalhsv.png',bgr)
    prvs = next